import { mkdir, readFile, readdir, rm, writeFile } from 'node:fs/promises';
import path from 'node:path';

const root = new URL('..', import.meta.url).pathname;
const readJson = async (file) => JSON.parse(await readFile(path.join(root, file), 'utf8'));
const projects = (await Promise.all((await readdir(path.join(root, 'catalog/projects'))).filter(f => f.endsWith('.json')).sort().map(f => readJson(`catalog/projects/${f}`)))).sort((a,b) => a.id.localeCompare(b.id));
const blueprints = await readJson('catalog/blueprints.json');
const out = path.join(root, 'site/dist');
const esc = (s) => String(s).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const label = (locale, en, zh) => locale === 'zh' ? zh : en;
const repoUrl = (repo) => `https://github.com/${repo}`;
const availability = (p, l) => p.source.visibility === 'public' ? label(l, 'Public source', '公开源码') : p.source.blueprint ? label(l, 'Private implementation · Public blueprint available', '私有实现 · 提供公开蓝图') : label(l, 'Private implementation', '私有实现');
const layout = (locale, title, body, metadata = '', depth = 1) => { const up = '../'.repeat(depth); return `<!doctype html><html lang="${locale === 'zh' ? 'zh-CN' : 'en'}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)} · Silkroad MCP</title><meta name="description" content="Silkroad MCP catalog"><link rel="stylesheet" href="${up}assets/site.css">${metadata}</head><body><header><nav aria-label="Primary"><a class="brand" href="/${locale}/">Silkroad MCP</a><a href="/${locale}/projects/">${label(locale,'Projects','项目')}</a><a href="/${locale}/blueprints/">${label(locale,'Blueprints','蓝图')}</a><a href="/${locale}/docs/">Docs</a><span class="language"><a href="${locale === 'en' ? '/zh/' : '/en/'}">${locale === 'en' ? '简体中文' : 'English'}</a></span></nav></header><main>${body}</main><footer>Silkroad MCP · <a href="/catalog.json">catalog.json</a> · <a href="/llms.txt">llms.txt</a></footer></body></html>`; };
const card = (p,l) => `<article class="card"><h2><a href="/${l}/projects/${p.id}/">${esc(p.name)}</a></h2><p>${esc(p.i18n[l].summary)}</p><p><span class="badge">${availability(p,l)}</span> <span class="badge">${p.capabilities.read ? label(l,'Read','读取') : ''}${p.capabilities.write ? ` + ${label(l,'Write','写入')}` : ''}</span> <span class="badge">${esc(p.status)}</span></p><a href="/${l}/projects/${p.id}/">${label(l,'View project','查看项目')}</a> · <a href="${repoUrl(p.source.repository)}">GitHub</a></article>`;
const projectPage = (p,l) => { const t=p.i18n[l], yes=v=>v?label(l,'Yes','是'):label(l,'No','否'); const section=(a,b)=>`<section><h2>${a}</h2>${b}</section>`; return layout(l,p.name,`<article><p class="eyebrow">${availability(p,l)}</p><h1>${esc(p.name)}</h1><p class="lead">${esc(t.summary)}</p>${section(label(l,'Summary','概要'),`<p>${esc(t.description)}</p>`)}${section(label(l,'Status','状态'),`<p>${esc(p.status)}</p>`)}${section(label(l,'Availability','可用性'),`<ul><li>${label(l,'Source','源码')}: ${esc(p.source.visibility)}</li><li>${label(l,'Repository','仓库')}: <a href="${repoUrl(p.source.repository)}">${esc(p.source.repository)}</a></li><li>${label(l,'Blueprint','蓝图')}: ${p.source.blueprint ? `<a href="/${l}/blueprints/${p.source.blueprint.split('/').pop()}/">${esc(p.source.blueprint)}</a>` : label(l,'Not available','不可用')}</li><li><a href="/catalog/projects/${p.id}.json">${label(l,'Machine-readable metadata','机器可读元数据')}</a></li></ul>`)}${section(label(l,'Capabilities','功能'),`<p>${label(l,'Read','读取')}: ${yes(p.capabilities.read)} · ${label(l,'Write','写入')}: ${yes(p.capabilities.write)} · ${label(l,'Confirmation required','需要确认')}: ${yes(p.capabilities.confirmation_required)}</p><h3>${label(l,'Main MCP tools','主要 MCP 工具')}</h3><ul>${p.tools.map(x=>`<li><code>${esc(x)}</code></li>`).join('')}</ul>`)}${section(label(l,'Authentication','认证'),`<p>${esc(p.auth.type.join(', '))}. ${esc(p.auth.notes)}</p>`)}${section(label(l,'Transport and service integration','传输与服务集成'),`<p>${esc(p.protocol.transports.join(', '))}</p><p>${label(l,'Official API','官方 API')}: ${yes(p.service.official_api)}. ${esc(p.service.mechanism.join('; '))}</p>`)}${section(label(l,'Safety','安全性'),`<p>${esc(p.risk.notes)}</p><p>${label(l,'Destructive actions','破坏性操作')}: ${esc(p.risk.destructive_actions.join(', ') || label(l,'None','无'))}</p>`)}${section(label(l,'Architecture','架构'),`<p>${esc(p.implementation.components.join(', '))}. ${esc(p.implementation.language.join(', '))}.</p>`)}${section(label(l,'Limitations','限制'),`<p>${esc(t.limitations)}</p>`)}</article>`, `<link rel="alternate" type="application/json" href="/catalog/projects/${p.id}.json">`, 3); };
const blueprintPage = (b,l) => {const t=b.i18n[l]; return layout(l,t.name,`<article><h1>${esc(t.name)}</h1><p class="lead">${esc(t.summary)}</p>${[['What it solves','解决的问题','solves'],['Architecture','架构','architecture'],['What is included','包含内容','included'],['What is intentionally excluded','有意不包含的内容','excluded'],['Security model','安全模型','security'],['Suitable use cases','适用场景','uses']].map(([en,zh,key])=>`<section><h2>${label(l,en,zh)}</h2><p>${esc(t[key])}</p></section>`).join('')}<section><h2>${label(l,'Related Silkroad projects','相关 Silkroad 项目')}</h2><ul>${b.relatedProjects.map(id=>{const p=projects.find(x=>x.id===id);return `<li><a href="/${l}/projects/${id}/">${esc(p.name)}</a></li>`}).join('')}</ul></section></article>`);};
await rm(out,{recursive:true,force:true}); await mkdir(path.join(out,'assets'),{recursive:true});
await writeFile(path.join(out,'assets/site.css'), `:root{font-family:ui-sans-serif,system-ui,sans-serif;color:#172033;background:#f8fafc}body{margin:0;line-height:1.55}header,footer{background:#101827;color:#e5edf8;padding:1rem max(1.25rem,calc((100% - 70rem)/2))}nav{display:flex;gap:1rem;align-items:center;flex-wrap:wrap}a{color:#075f9e}.brand{font-weight:700;color:inherit;text-decoration:none}.language{margin-left:auto}header a,footer a{color:#d7ecff}main{max-width:70rem;margin:auto;padding:3rem 1.25rem}h1{font-size:clamp(2rem,6vw,3.5rem);line-height:1.1}.lead{font-size:1.25rem;max-width:48rem}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(250px,1fr));gap:1rem}.card{background:white;border:1px solid #dce4ee;border-radius:.75rem;padding:1.25rem}.badge,.eyebrow{display:inline-block;border:1px solid #9aacbf;border-radius:999px;padding:.12rem .5rem;font-size:.85rem}section{margin:2rem 0}code{background:#e7eef6;padding:.1rem .3rem;border-radius:.2rem}footer{margin-top:3rem}@media(prefers-color-scheme:dark){:root{color:#e5edf8;background:#101827}.card{background:#172033;border-color:#334155}code{background:#263548}a{color:#77c7ff}}`);
const write=(file,content)=>mkdir(path.dirname(path.join(out,file)),{recursive:true}).then(()=>writeFile(path.join(out,file),content));
await write('index.html', `<!doctype html><meta charset="utf-8"><meta http-equiv="refresh" content="0; url=/en/"><title>Silkroad MCP</title><p><a href="/en/">English</a> · <a href="/zh/">简体中文</a></p>`);
for (const l of ['en','zh']) { const intro=label(l,'Silkroad MCP is a collection of MCP servers, reusable components, and implementation blueprints for connecting AI to services that lack first-party MCP integrations.','Silkroad MCP 汇集 MCP 服务器、可复用组件和实现蓝图，帮助 AI 连接尚未提供官方 MCP 集成的服务。'); await write(`${l}/index.html`,layout(l,'Home',`<article><h1>Silkroad MCP</h1><p class="lead">${intro}</p><p>${label(l,'Focused on Asian services, device integrations, and practical interoperability—without being limited to any region or provider.','聚焦亚洲服务、设备集成和实际互操作性，但不局限于任何地区或提供商。')}</p><h2>${label(l,'Projects','项目')}</h2><div class="grid">${projects.map(p=>card(p,l)).join('')}</div><h2>${label(l,'Blueprints','蓝图')}</h2><div class="grid">${blueprints.map(b=>`<article class="card"><h3><a href="/${l}/blueprints/${b.id}/">${esc(b.i18n[l].name)}</a></h3><p>${esc(b.i18n[l].summary)}</p></article>`).join('')}</div><p><strong>${label(l,'Availability labels','可用性标签')}:</strong> ${label(l,'Open means source is public; Private means production code is not published; Blueprint available means a reusable public design is available.','公开表示源码公开；私有表示生产代码未发布；提供公开蓝图表示可复用的公开设计可用。')}</p></article>`)); await write(`${l}/projects/index.html`,layout(l,label(l,'Projects','项目'),`<h1>${label(l,'Projects','项目')}</h1><div class="grid">${projects.map(p=>card(p,l)).join('')}</div>`)); await write(`${l}/blueprints/index.html`,layout(l,label(l,'Blueprints','蓝图'),`<h1>${label(l,'Blueprints','蓝图')}</h1><div class="grid">${blueprints.map(b=>`<article class="card"><h2><a href="/${l}/blueprints/${b.id}/">${esc(b.i18n[l].name)}</a></h2><p>${esc(b.i18n[l].summary)}</p></article>`).join('')}</div>`)); for(const p of projects) await write(`${l}/projects/${p.id}/index.html`,projectPage(p,l)); for(const b of blueprints) await write(`${l}/blueprints/${b.id}/index.html`,blueprintPage(b,l)); const docs=await Promise.all(['architecture','security','publishing','project-status'].map(async id=>[id,await readFile(path.join(root,`docs/${id}.md`),'utf8')])); await write(`${l}/docs/index.html`,layout(l,'Docs',`<h1>Docs</h1><p>${l==='zh'?'长篇技术文档以英语为准；此处提供原始 Markdown 链接。':'Long-form technical documents are canonical in English; source Markdown is linked below.'}</p><ul>${docs.map(([id])=>`<li><a href="/docs/${id}.md">${id}</a></li>`).join('')}</ul>`)); }
for (const [id,contents] of await Promise.all(['architecture','security','publishing','project-status'].map(async id=>[id,await readFile(path.join(root,`docs/${id}.md`),'utf8')]))) await write(`docs/${id}.md`,contents);
const catalog={schemaVersion:'1.0.0',projects,blueprints}; await write('catalog.json',JSON.stringify(catalog,null,2)+'\n'); for(const p of projects) await write(`catalog/projects/${p.id}.json`,JSON.stringify(p,null,2)+'\n');
const llms=`# Silkroad MCP\n\nSilkroad MCP is a multilingual discovery hub for MCP servers, reusable components, and implementation blueprints.\n\n## Projects\n${projects.map(p=>`- [${p.name}](/en/projects/${p.id}/): ${p.i18n.en.summary}`).join('\n')}\n\n## Blueprints\n${blueprints.map(b=>`- [${b.i18n.en.name}](/en/blueprints/${b.id}/): ${b.i18n.en.summary}`).join('\n')}\n\n## Important resources\n- [Machine-readable catalog](/catalog.json)\n- [Security documentation](/docs/security.md)\n- [Architecture documentation](/docs/architecture.md)\n`; await write('llms.txt',llms); await write('zh/llms.txt',`# Silkroad MCP\n\nSilkroad MCP 是面向 MCP 服务器、可复用组件和实现蓝图的多语言发现中心。\n\n${projects.map(p=>`- [${p.name}](/zh/projects/${p.id}/): ${p.i18n.zh.summary}`).join('\n')}\n`);
const table=projects.map(p=>`| [${p.name}](catalog/projects/${p.id}.json) | ${p.source.visibility[0].toUpperCase()+p.source.visibility.slice(1)} | ${p.source.blueprint ? 'Yes' : 'No'} | ${p.status[0].toUpperCase()+p.status.slice(1)} | ${p.capabilities.read?'Yes':'No'} | ${p.capabilities.write?'Yes':'No'} |`).join('\n'); const readme=await readFile(path.join(root,'README.md'),'utf8'); const replacement=`<!-- catalog:start -->\n| Project | Source | Blueprint | Status | Read | Write |\n| --- | --- | --- | --- | --- | --- |\n${table}\n<!-- catalog:end -->`; await writeFile(path.join(root,'README.md'),readme.replace(/<!-- catalog:start -->[\s\S]*?<!-- catalog:end -->/,replacement));
